baseURL       = "https://ygterdem.github.io/medynaes"
languageCode  = "en-us"
title         = "Medynaes"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Google Analitycs
  googleAnalitycsID = "G-7Y14W6ZVN4"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/Haydar.png"
    heading               = "Creating Games For WebGL"
    tagline               = "MECHANICS DYNAMICS AESTHETICS"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Play On Yandex Games"
    secondary_button_url  = "https://yandex.com/games/developer?name=ErdemY#"


  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      email   = "erdemygt@protonmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Discord"
          url  = "https://discord.com/invite/6j4KjH7ygV"
        [[params.footer.social.link]]
          name = "Yandex Games"
          url  = "https://yandex.com/games/developer?name=ErdemY#"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/MEDYNAES"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/medynaes/"